version: '2'
services:
  api:
    container_name: mind-api
    build: ./api
    ports:
    - "5000:5000"
    volumes:
    - apilog:/var/log
    links:
    - mind-db
  mind-db:
    container_name: mind-db
    entrypoint: dgraph
    ports:
    - "8080:8080"
    image: dgraph/dgraph
    volumes:
    - datavolume:/data
volumes:
  apilog: {}
  datavolume: {}
