version: '2'
services:
  api:
    container_name: mind-api
    build: ./api
    ports:
    - "5000:5000"
    volumes:
    - apilog:/var/log
    links:
    - mind-db
  mind-db:
    container_name: mind-db
    ports:
    - "7474:7474"
    - "7687:7687"  
    image: neo4j
    volumes:
    - datavolume:$HOME/neo4j/data
    environment:
    - NEO4J_AUTH=none
volumes:
  apilog: {}
  datavolume: {}
