version: '2'
services:
  mind-api:
    container_name: mind-api
    image: mind-api
    build: ./api
    ports:
    - "5000:9000"
    volumes:
    - ./.log/mind-api:/var/log
    environment:
    - MIND_NEO4J_URL=http://mind-db:7474
    - MIND_SEARCH_URL=http://mind-search:9200
    links:
    - mind-db
    - mind-search
  mind-facet.ideas:
    container_name: mind-facet.ideas
    image: mind-facet.ideas
    build: ./facets/ideas
    ports:
    - "5010:9010"
    environment:
    - MIND_API_URL=http://mind-api:9000
    links:
    - mind-api
  mind-search:
    container_name: mind-search
    image: kiasaki/alpine-elasticsearch 
    ports:
    - "5007:9200"
  mind-db:
    container_name: mind-db
    image: thetallgrassnet/alpine-neo4j
    ports:
    - "5008:7474"
    environment:
    - NEO4J_AUTH=none
    volumes:
    - ./.data/mind-db:$HOME/neo4j/data
volumes:
  apilog: {}
  datavolume: {}
