version: '2'
services:
  mind-api:
    container_name: mind-api
    image: mind-api
    build: ./api
    ports:
    - "5000:9000"
    volumes:
    - apilog:/var/log
    environment:
    - MIND_DGRAPH_URL=http://mind-db:8080
    links:
    - mind-db
    - mind-search
  mind-facet.ideas:
    container_name: mind-facet.ideas
    image: mind-facet.ideas
    build: ./facets/ideas
    ports:
    - "5010:9010"
    environment:
    - MIND_API_URL=http://mind-api:9000
    links:
    - mind-api
  mind-search:
    container_name: mind-search
    image: kiasaki/alpine-elasticsearch 
    ports:
    - "9200:9200"
    environment:
    - MIND_SEARCH_URL=http://mind-search:9200
  mind-db:
    container_name: mind-db
    image: mind-db
    entrypoint: dgraph
    ports:
    - "5008:8080"
    image: dgraph/dgraph
    volumes:
    - datavolume:/data
volumes:
  apilog: {}
  datavolume: {}
